// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "customer-test",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:e7ac3e37-a7dd-4791-aef5-1a72207c068c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_7HXuapbFc",
    "aws_user_pools_web_client_id": "31epivj6341d2eotd3ae2p9bbf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://x75duubd5fdjjacposc3ren2ly.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-shhntpfuyzgkjbh5x72cuh3mee"
};


export default awsmobile;
